export const USER_ACTION_TYPES = {
  SET_USER_TO_DEFAULT: '@@user/SET_USER_TO_DEFAULT',
  FETCH_USER_START: '@@user/FETCH_USER_START',
  FETCH_USER_FAILURE: '@@user/FETCH_USER_FAILURE',
  FETCH_USER_SUCCESS: '@@user/FETCH_USER_SUCCESS',
};
