export const COLLECTION_ACTION_TYPES = {
  FETCH_COLLECTION_START: '@@collection/FETCH_COLLECTION_START',
  FETCH_COLLECTION_FAILURE: '@@collection/FETCH_COLLECTION_FAILURE',
  FETCH_COLLECTION_SUCCESS: '@@collection/FETCH_COLLECTION_SUCCESS',
};
