export const COLLECTION_ACTION_TYPES = {
  SET_CURRENT_COLLECTION: '@@collection/SET_CURRENT_COLLECTION',
  SET_FULL_COLLECTION: '@@collection/SET_FULL_COLLECTION',
  TOGGLE_BOOKMARK: '@@collection/TOGGLE_BOOKMARK',
};
