export const ITEM_ACTION_TYPES = {
  FETCH_ITEM_START: '@@item/FETCH_ITEM_START',
  FETCH_ITEM_FAILURE: '@@item/FETCH_ITEM_FAILURE',
  FETCH_ITEM_SUCCESS: '@@item/FETCH_ITEM_SUCCESS',
  SET_COLOR_AND_ID: '@@item/SET_COLOR_AND_ID',
  SET_CURRENT_SIZE: '@@item/SET_CURRENT_SIZE',
  CLEAR_ITEM: '@@item/CLEAR_ITEM',
};
