export const CART_ACTION_TYPES = {
  CHANGE_QUANTITY: '@@cart/CHANGE_QUANTITY',
  DELETE_FROM_CART: '@@cart/DELETE_FROM_CART',
  ADD_TO_CART: '@@cart/ADD_TO_CART',
  CART_TO_INITIAL_STATE: '@@cart/CART_TO_INITIAL_STATE',
  TOGGLE_CART: '@@cart/TOGGLE_CART',
  SET_CART_TOTAL: '@@cart/SET_CART_TOTAL',
  TOGGLE_CART_STATUS: '@@cart/TOGGLE_CART_STATUS',
};
